### ISSUE TITLE
Subroute loading state gets focus, resolved page never does

### ISSUE THREAD

**Issue by BrennanRoberts** [ember-a11y/ember-a11y#61]
When drilling down from `/` into `/foo/bar`, `foo/loading.hbs` gets focused, but `foo/bar.hbs` never does.

Test case repository: https://github.com/BrennanRoberts/ember-a11y-loading-focus-test-case

### Reproduction
1. Visit `/`
2. Click link to `/foo`, observe that both the loading state and the foo template receive focus
3. Go back to `/`
4. Click link to `/foo/bar`

### Actual
Loading state gets focused. When loading finishes, the resulting page gets focused.

### Expected
Only loading state gets focused.

**Comment by nathanhammond** [comment]
Note that I never recommend actual loading routes, and instead recommend loading substates. (`foo-loading` instead of `foo/loading`.)

**Comment by BrennanRoberts** [comment]
@nathanhammond Here's a branch using that method: https://github.com/BrennanRoberts/ember-a11y-loading-focus-test-case/tree/loading-substates.

That appears to make the problem worse: moving from `/` to `/foo` only announces the loading state, not the loaded result, unlike the route method.

**Comment by nathanhammond** [comment]
What's happening here is actually correct. Here is your route tree:

- application
  - loading
  - index
  - foo
    - loading
    - bar

***

Your reproduction:

a. Visit `/`
  - currentRoute: `application.index`

b. Click link to `/foo`, observe that both the loading state and the foo template receive focus.
  - Transition to `application/loading`
  - Continue transition to `application/foo`

c. Go back to `/`
  - currentRoute: `application.index`

d. Click link to `/foo/bar`
  - Transition to `application/loading`
  - Continue transition to `application/foo`
  - Continue transition to `application/foo/loading`
  - Continue transition to `application/foo/bar`

In both `B` and `D` the pivot route is one beneath the application route. (Read: "the largest area of the application which is being changed.") That is the region whose focus should be managed. You're asking to focus a second-level change.

**Comment by BrennanRoberts** [comment]
@nathanhammond thanks for your response 🙏 .

> b. Click link to /foo, observe that both the loading state and the foo template receive focus.

This is not consistent with what I'm seeing. When I add a visual focus state and log focus changes using:
```
const oldFocus = HTMLElement.focus;
HTMLElement.focus = function() {
  console.log("focus", this);
  oldFocus.apply(this, arguments);
};
```
 and click the link to `/foo` from the home page, only the loading state ever receives focus. I've updated the repo ( still the `loading-substates` branch) with the visual focus indicator and console logging.

> In both B and D the pivot route is one beneath the application route. (Read: "the largest area of the application which is being changed.") That is the region whose focus should be managed. You're asking to focus a second-level change.

Ah, I understand the pivot route concept now, thanks. Still not sure how to deal with this particular situation though. In our case, `/foo` is a small wrapper; `/bar` is where the action is, so we want to make sure its content gets announced.

**Comment by nathanhammond** [comment]
> This is not consistent with what I'm seeing.

Can you check your example with 0.2.0? I addressed what I believe to be the remaining balance of outstanding issues with that release. I did my review with `master` from your test repo and `ember-a11y@0.2.0` and the behavior matched my expectations.

> In our case, /foo is a small wrapper; /bar is where the action is, so we want to make sure its content gets announced.

It (likely) will! When you focus the region you're setting it to the *parent*. AT will *start* reading at that point, and the reading of the linearization will progress from there. The content in `/foo/bar` will eventually be read with the caveat that it may read the contents of `/foo/loading` if it gets there before `/foo/bar` is populated. If that happens it will either:

- Complete reading of `/foo/loading` while waiting for `/foo/bar`. The `/foo/loading => /foo/bar` transition will be silent. (I'd like to be able to do something about this but we don't have programmatic AT control on the web.)
- Stop reading `/foo/loading` abruptly when `/foo/bar` loads in to replace it. (Ungraceful cue of content change.)

If you consistently have either of those problems you should hoist the latent behavior from `/foo/bar` to `/foo` so that the it blocks loading until both will be able to be rendered simultaneously.

**Comment by BrennanRoberts** [comment]
> Can you check your example with 0.2.0?

Yeah, still happening there. I've updated [master](https://github.com/BrennanRoberts/ember-a11y-loading-focus-test-case) with the ember-a11y version bump and focus indicator.

> It (likely) will! When you focus the region you're setting it to the parent. AT will start reading at that point, and the reading of the linearization will progress from there.

Makes complete sense, thank you!

**Comment by nathanhammond** [comment]
Thanks for the persistence on this, I'm splitting it from this issue and filing it as a separate bug.

**Comment by nathanhammond** [comment]
@BrennanRoberts Filed over at #72. I don't have time for a bit to run all of the tests required to attempt this change, but I did document pretty closely what I think needed to be explored.

Is that something you could investigate and open a PR for?
